from __future__ import annotations

from core_types import PresentationBrief, Project, ProjectFile, SourceBundle, UserIntent

from methodology_engine.clarifier import RequirementClarifier


class BriefGenerator:
    def __init__(self) -> None:
        self._clarifier = RequirementClarifier()

    def generate(
        self,
        *,
        project: Project,
        source_bundle: SourceBundle,
        project_files: list[ProjectFile],
        user_intent: UserIntent | None,
        force_regenerate: bool,
    ) -> PresentationBrief:
        assessment = self._clarifier.assess(source_bundle, user_intent)
        intent = user_intent or source_bundle.user_intent
        recommended_page_count = self._recommend_page_count(source_bundle, project_files, intent)
        return PresentationBrief(
            project_id=project.id,
            source_bundle_id=source_bundle.id,
            presentation_goal=self._build_presentation_goal(project, intent),
            target_audience=(intent.audience if intent and intent.audience else "general audience"),
            core_message=self._build_core_message(project, source_bundle, intent),
            storyline=self._build_storyline(source_bundle, intent),
            recommended_page_count=recommended_page_count,
            tone=self._build_tone(intent),
            style_preferences=intent.style_preferences if intent else [],
            risks=self._build_risks(source_bundle, assessment, force_regenerate),
            assumptions=self._build_assumptions(source_bundle, assessment),
            metadata={
                "generation_mode": "methodology_engine_v1",
                "clarification": {
                    "is_sufficient": assessment.is_sufficient,
                    "missing_fields": assessment.missing_fields,
                    "suggested_questions": assessment.suggested_questions,
                },
                "source_mode": source_bundle.source_mode,
            },
        )

    def _build_presentation_goal(self, project: Project, intent: UserIntent | None) -> str:
        if intent and intent.purpose:
            return intent.purpose
        return project.description or f"Generate a presentation for project {project.name}"

    def _build_core_message(self, project: Project, source_bundle: SourceBundle, intent: UserIntent | None) -> str:
        if intent and intent.emphasize_points:
            return intent.emphasize_points[0]
        if source_bundle.normalized_markdown:
            first_line = next((line.strip("- ") for line in source_bundle.normalized_markdown.splitlines() if line.strip()), None)
            if first_line:
                return first_line
        return f"{project.name} should present a focused and evidence-based narrative."

    def _build_storyline(self, source_bundle: SourceBundle, intent: UserIntent | None) -> str:
        parts: list[str] = []
        if intent and intent.scenario:
            parts.append(f"Context: {intent.scenario}")
        if source_bundle.citations:
            parts.append("Sources: " + " -> ".join(source_bundle.citations[:5]))
        if intent and intent.emphasize_points:
            parts.append("Highlights: " + " -> ".join(intent.emphasize_points[:4]))
        return " | ".join(parts) if parts else "Problem -> Evidence -> Insight -> Recommendation"

    def _build_tone(self, intent: UserIntent | None) -> str:
        if intent and intent.style_preferences:
            return intent.style_preferences[0]
        return "professional"

    def _build_risks(self, source_bundle: SourceBundle, assessment, force_regenerate: bool) -> list[str]:
        risks: list[str] = []
        if not force_regenerate:
            risks.append("brief is generated by rule-based methodology engine v1")
        if source_bundle.status != "ready":
            risks.append("source bundle contains warnings and may require review")
        if not assessment.is_sufficient:
            risks.append("user intent is incomplete and may affect narrative accuracy")
        return risks

    def _build_assumptions(self, source_bundle: SourceBundle, assessment) -> list[str]:
        assumptions = ["research enrichment is not connected yet"]
        if source_bundle.source_file_ids:
            assumptions.append("uploaded files are the primary evidence base")
        if assessment.missing_fields:
            assumptions.append("missing clarification fields will be filled in later review")
        return assumptions

    def _recommend_page_count(self, source_bundle: SourceBundle, project_files: list[ProjectFile], intent: UserIntent | None) -> int:
        if intent and intent.desired_page_count:
            return intent.desired_page_count
        chunk_factor = max(1, len(source_bundle.page_chunks) // 3)
        file_factor = max(1, len(project_files) * 2)
        return max(8, min(20, max(chunk_factor, file_factor)))